@startuml

actor "pengisi survey" as user
node "web e-survey kampus"{
    node "Model" as model
    node "Controller" as controller
    node "View" as view
}

database "Mysql" as mysql

user --> view : 1
view --> controller: 2
view --> model : 3
view --> mysql : 4
view --> user : 5

@enduml